name: Node CI
on:
  push:
    branches:
      - main

jobs:
  quality_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
        env:
          NODE_ENV: production
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
